version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: plm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-plm_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-plm_pass}
      POSTGRES_DB: ${POSTGRES_DB:-plm_db}
    ports:
      - '5432:5432'
    volumes:
      - plm_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U plm_user -d plm_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  plm_pgdata:
    driver: local
